# Generated by Django 2.0.3 on 2018-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180320_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
